### ISSUE TITLE
Problem when downloading data in wrong soa type

### ISSUE THREAD

**Issue by ailishgraham** [npct/pct-outputs-regional-R#1]
Download breaks when trying to download data in MSOA rather than LSOA resolution - no error message to help de-bug

get_pct_rnet(region="isle-of-wight")
trying URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/rnet.Rds'
Error in utils::download.file(url = u_file, destfile = destfile, mode = "wb") : 
  cannot open URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/rnet.Rds'
In addition: Warning message:
In utils::download.file(url = u_file, destfile = destfile, mode = "wb") :
  cannot open URL 'https://github.com/npct/pct-outputs-regional-R/raw/master/commute/msoa/isle-of-wight/rnet.Rds': HTTP status was '404 Not Found'

**Comment by usr110** [comment]
How are you trying to download this data? From the app?
I believe the `route-network` only exists at the `LSOA` - not `MSOA`, level, hence you're getting this error

**Comment by Robinlovelace** [comment]
Heads-up @usr110 I think this is an issue with `pct` package. Please can you open the issue here: https://github.com/ITSLeeds/pct/issues

All the best, from the PCT Advanced Workshop!

**Comment by usr110** [comment]
Thanks for the clarification @Robinlovelace !
